language: php

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
  fast_finish: true

install:
  - composer install

script: phpunit
notifications: { email: false }